#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=book_management
#spring.datasource.username=postgres
#spring.datasource.password=${LOCAL_BOOK_PASSWORD}
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

logging:
  level:
    com:
      example:
        bookmanagementsystem: TRACE

spring:
  datasource:
    url: '${LOCAL_BOOK_POSTGRES:jdbc:postgresql://localhost:5432/postgres?currentSchema=book_management}'
    username: '${LOCAL_BOOK_USERNAME:postgres}'
    password: '${LOCAL_BOOK_PASSWORD:postgres}'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: '${BOOK_SHOW_SQL:true}'
