server:
  port: 8081
app:
  version: 1.0.1
logging:
  level:
    com:
      pluralsight:
        conferencedemo: TRACE
spring:
  flyway:
    enabled: true
  datasource:
    url: '${LOCAL_CONFERENCE_POSTGRES:jdbc:postgresql://localhost:5432/conference_app?currentSchema=conference_app}'
    username: '${LOCAL_CONFERENCE_USERNAME:postgres}'
    password: '${LOCAL_CONFERENCE_PASSWORD:QQ1234!!}'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: '${CONFERENCE_SHOW_SQL:true}'
      jdbc:
        lob:
          non_contextual_creation: '${CONFERENCE_NON_CONTEXTUAL_CREATION:true}'
  consumer:
    bootstrap-servers: localhost:9092
    group-id: consumer-1
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: com.example.*
      auto.offset.reset: earliest